/* Main.c file generated by New Project wizard
 *
 * Created:   Mon Apr 20 2020
 * Processor: dsPIC33FJ32MC202
 * Compiler:  MPLAB XC16
 */

#include <p33FJ32MC202.h>

int main (void)
 { 
   // Write your code here
   while (1)
      ;
   return 0;
 }   
